### ISSUE TITLE
If i want to puring myself model, what I can do ?

### ISSUE THREAD

**Issue by SongLongZhang** [anonymous47823493/FNNP#1]

**Comment by anonymous47823493** [comment]
Our submission to CVPR is still under review, so the best we may offer is technical suggestion before our final publicity is finalized. If our pratical description in the paper manuscript is not clear enough to you, we are more than happy to discuss implementation details here.

**Comment by atrah22** [comment]
Hello,
Is the paper accepted at CVPR ? It would be great to see the training implementation code aswell
